Repository cr-ste-justine/clin-frontend, pull requests merged in 2020-02, with the labels that each got.

#125 autoselect newly created query in statement
  client/src/components/Query/Statement.jsx
Labels: bug

#126 remove filter if instruction becomes empty
  client/src/components/Query/Filter/index.jsx
Labels: bug

#127 fixed numericalcomparison empty state
  client/src/components/Query/Filter/index.jsx
Labels: bug

#128 check all / uncheck all
  client/src/components/Query/Filter/Generic.jsx
  client/src/components/Query/Filter/GenericBoolean.jsx
  client/src/components/Query/Filter/Specific.jsx
Labels: bug

#129 bug/specific filter
  client/src/components/Query/Filter/Specific.jsx
Labels: bug

#146 fix inability to remove default statement from profile
  client/src/components/Query/Statement.jsx
Labels: bug

#147 only display observed hpo and add link
  client/src/components/screens/PatientVariant/index.jsx
  client/src/locales/en.js
  client/src/locales/fr.js
Labels: enhancement

#148 intl numbers
  client/src/components/Query/Filter/Composite.jsx
  client/src/components/Query/Filter/Generic.jsx
  client/src/components/Query/Filter/GenericBoolean.jsx
  client/src/components/Query/Filter/Specific.jsx
  client/src/components/Query/index.jsx
  client/src/components/screens/PatientVariant/components/VariantNavigation.jsx
  client/src/locales/en.js
  client/src/locales/fr.js
Labels: enhancement

#150 WIP : bug/qa fixes
  client/src/components/Query/Statement.jsx
  client/src/locales/en.js
  client/src/locales/fr.js
  client/src/reducers/variant.js
Labels: WIP, bug, enhancement

#149 styling/functionality/composite filter
  client/src/components/Query/Filter/Composite.jsx
  client/src/components/Query/Filter/Generic.jsx
  client/src/components/Query/Filter/NumericalComparison.jsx
  client/src/components/Query/Filter/index.jsx
  client/src/components/Query/Filter/widgets/NumericalComparisonWidget.jsx
  client/src/components/Query/Operator.jsx
  client/src/components/Query/Statement.jsx
  client/src/components/Query/index.jsx
  client/src/components/Query/styles/filter.module.scss
  client/src/components/screens/PatientVariant/components/VariantNavigation.jsx
  pnpm-lock.yaml
Labels: WIP
